### ISSUE TITLE
Transaction api endpoint returns invalid or wrongly formated Bech32 addresses

### ISSUE THREAD

**Issue by JosipSylo** [btccom/ExplorerAPIDoc#5]
When requesting:
https://chain.api.btc.com/v3/tx/212e24565a5e26d1bc8de106fa99d40755870127c7d64c125a151c311ffba904
One of the output addresses shows: "2a4ee3c55e0bf67b3eb480b5301a0cb6af050e05"
If we check
https://btc.com/212e24565a5e26d1bc8de106fa99d40755870127c7d64c125a151c311ffba904
we can see that it should be: "bc1q9f8w8327p0m8k045sz6nqxsvk6hs2rs94nh9s5".

The same thing happens for all Bech32/segwit addresses.

**Comment by dubuqingfeng** [comment]
fixed.
